"""add_action_intent_table

Revision ID: 10a3be58812f
Revises: 1b7c6d5e4f3a
Create Date: 2026-02-16 12:00:36.456910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a3be58812f'
down_revision: Union[str, Sequence[str], None] = '1b7c6d5e4f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_intents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decision_trace_id', sa.Uuid(), nullable=True),
    sa.Column('intent_type', sa.Enum('ach_transfer', 'acats_transfer', 'rebalance', 'tax_loss_harvest', 'open_account', 'custom', name='actionintenttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'processing', 'executed', 'failed', 'cancelled', name='actionintentstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('impact_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_trace_id'], ['decision_traces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_intents_status'), 'action_intents', ['status'], unique=False)
    op.create_index(op.f('ix_action_intents_user_id'), 'action_intents', ['user_id'], unique=False)
    op.add_column('agent_action_policies', sa.Column('require_mfa', sa.Boolean(), nullable=False))
    op.add_column('agent_sessions', sa.Column('vanish_mode', sa.Boolean(), nullable=False))
    op.add_column('bank_transactions', sa.Column('is_commingled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cash_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('debt_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('financial_memories', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('investment_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_accounts', 'is_business')
    op.drop_column('financial_memories', 'preferences')
    op.drop_column('debt_accounts', 'is_business')
    op.drop_column('cash_accounts', 'is_business')
    op.drop_column('bank_transactions', 'is_commingled')
    op.drop_column('agent_sessions', 'vanish_mode')
    op.drop_column('agent_action_policies', 'require_mfa')
    op.drop_index(op.f('ix_action_intents_user_id'), table_name='action_intents')
    op.drop_index(op.f('ix_action_intents_status'), table_name='action_intents')
    op.drop_table('action_intents')
    # ### end Alembic commands ###
