"""add_execution_manifest_to_action_intent

Revision ID: 206d4033c67a
Revises: 315993611f09
Create Date: 2026-02-16 16:53:54.127403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206d4033c67a'
down_revision: Union[str, Sequence[str], None] = '315993611f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_intents', sa.Column('execution_manifest', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_intents', 'execution_manifest')
    # ### end Alembic commands ###
