"""add_entity_model

Revision ID: 21ba92652443
Revises: 82a6e4e7cd60
Create Date: 2026-03-03 05:45:10.689769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '21ba92652443'
down_revision: Union[str, Sequence[str], None] = '82a6e4e7cd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('personal', 'c_corp', 's_corp', 'llc', 'spv', 'trust', name='entitytype'), server_default='personal', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    with op.batch_alter_table('cash_accounts') as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cash_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_foreign_key('fk_cash_accounts_entities', 'entities', ['entity_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('debt_accounts') as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_debt_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_foreign_key('fk_debt_accounts_entities', 'entities', ['entity_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('investment_accounts') as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_investment_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_foreign_key('fk_investment_accounts_entities', 'entities', ['entity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_accounts') as batch_op:
        batch_op.drop_constraint('fk_investment_accounts_entities', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_investment_accounts_entity_id'))
        batch_op.drop_column('entity_id')

    with op.batch_alter_table('debt_accounts') as batch_op:
        batch_op.drop_constraint('fk_debt_accounts_entities', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_debt_accounts_entity_id'))
        batch_op.drop_column('entity_id')

    with op.batch_alter_table('cash_accounts') as batch_op:
        batch_op.drop_constraint('fk_cash_accounts_entities', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_accounts_entity_id'))
        batch_op.drop_column('entity_id')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
