"""add_capabilities_to_accounts

Revision ID: 315993611f09
Revises: 61e3509da185
Create Date: 2026-02-16 12:40:56.985022

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '315993611f09'
down_revision: Union[str, Sequence[str], None] = '61e3509da185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_accounts', sa.Column('capabilities', sa.JSON(), nullable=False))
    op.add_column('investment_accounts', sa.Column('capabilities', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_accounts', 'capabilities')
    op.drop_column('cash_accounts', 'capabilities')
    # ### end Alembic commands ###
