"""add notifications table

Revision ID: 89647041d785
Revises: 91269ba828fa
Create Date: 2026-02-18 17:33:07.301114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89647041d785'
down_revision: Union[str, Sequence[str], None] = '91269ba828fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('low_emergency_fund', 'tax_loss_harvesting', 'data_stale', 'sync_failure', 'policy_breach', 'general', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('agent_action_policies', sa.Column('require_mfa', sa.Boolean(), nullable=False))
    op.add_column('agent_sessions', sa.Column('vanish_mode', sa.Boolean(), nullable=False))
    op.add_column('bank_transactions', sa.Column('is_commingled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cash_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('debt_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('financial_memories', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('investment_accounts', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_accounts', 'is_business')
    op.drop_column('financial_memories', 'preferences')
    op.drop_column('debt_accounts', 'is_business')
    op.drop_column('cash_accounts', 'is_business')
    op.drop_column('bank_transactions', 'is_commingled')
    op.drop_column('agent_sessions', 'vanish_mode')
    op.drop_column('agent_action_policies', 'require_mfa')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
