"""add_financial_memory

Revision ID: 9da2b903e34f
Revises: b8a4c0f4a9d1
Create Date: 2026-01-31 19:31:00.111026

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9da2b903e34f'
down_revision: Union[str, Sequence[str], None] = 'b8a4c0f4a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', name='filingstatus'), nullable=True),
    sa.Column('num_dependents', sa.Integer(), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('federal_tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('state_tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('capital_gains_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('retirement_age', sa.Integer(), nullable=True),
    sa.Column('current_retirement_savings', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_retirement_contribution', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employer_match_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_social_security', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('desired_retirement_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('home_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mortgage_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mortgage_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risktolerance'), nullable=True),
    sa.Column('investment_horizon_years', sa.Integer(), nullable=True),
    sa.Column('monthly_savings_target', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('emergency_fund_target_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_memories_user_id'), 'financial_memories', ['user_id'], unique=True)
    op.create_table('memory_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('user_input', 'calculator', 'account_sync', 'agent', name='memoryeventsource'), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_events_user_id'), 'memory_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_events_user_id'), table_name='memory_events')
    op.drop_table('memory_events')
    op.drop_index(op.f('ix_financial_memories_user_id'), table_name='financial_memories')
    op.drop_table('financial_memories')
    # ### end Alembic commands ###
