"""extend_recommendation_status_and_add_supersession

Revision ID: a04c014d9db5
Revises: b3d9f4e8c2a1
Create Date: 2026-03-12 17:18:56.879754

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a04c014d9db5'
down_revision: Union[str, Sequence[str], None] = 'b3d9f4e8c2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superseded_recommendation_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('superseded_by_recommendation_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'accepted', 'dismissed', 'needs_review', 'cautious', 'blocked', 'superseded', 'resolved', name='recommendationstatus'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_recommendations_superseded_id', 'recommendations', ['superseded_recommendation_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_recommendations_superseded_by_id', 'recommendations', ['superseded_by_recommendation_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recommendations_superseded_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_recommendations_superseded_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'accepted', 'dismissed', 'needs_review', 'cautious', 'blocked', 'superseded', 'resolved', name='recommendationstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('superseded_by_recommendation_id')
        batch_op.drop_column('superseded_recommendation_id')

    # ### end Alembic commands ###
