"""add_blocked_to_recommendation_review_status

Revision ID: a582acc13bf7
Revises: a04c014d9db5
Create Date: 2026-03-12 17:19:24.366058

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a582acc13bf7'
down_revision: Union[str, Sequence[str], None] = 'a04c014d9db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_reviews', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'resolved', 'dismissed', 'converted_to_correction', 'superseded', name='recommendationreviewstatus'),
               type_=sa.Enum('open', 'resolved', 'dismissed', 'converted_to_correction', 'superseded', 'blocked', name='recommendationreviewstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_reviews', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'resolved', 'dismissed', 'converted_to_correction', 'superseded', 'blocked', name='recommendationreviewstatus'),
               type_=sa.Enum('open', 'resolved', 'dismissed', 'converted_to_correction', 'superseded', name='recommendationreviewstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
