"""initial_schema

Revision ID: b7b454c34159
Revises: 
Create Date: 2026-03-31 17:03:54.615461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'b7b454c34159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cards_issuer'), ['issuer'], unique=False)

    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('providers', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('security_type', sa.Enum('stock', 'etf', 'mutual_fund', 'bond', 'crypto', 'cash', 'option', 'other', name='securitytype'), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close_price_as_of', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_ticker'), ['ticker'], unique=False)

    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clerk_id'), ['clerk_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)

    op.create_table('waitlist_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('net_worth_bracket', sa.String(length=50), nullable=True),
    sa.Column('interested_tier', sa.String(length=50), nullable=True),
    sa.Column('source_tool', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_waitlist_users_referral_code'), ['referral_code'], unique=True)

    op.create_table('action_approvals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='actionapprovalstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_approvals_user_id'), ['user_id'], unique=False)

    op.create_table('agent_action_policies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('require_confirmation', sa.Boolean(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='actionpolicystatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_action_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_action_policies_user_id'), ['user_id'], unique=False)

    op.create_table('agent_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'paused', name='sessionstatus'), nullable=False),
    sa.Column('vanish_mode', sa.Boolean(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('alternative_assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('private_equity', 'angel_investment', 'venture_capital', 'hedge_fund', 'limited_partnership', 'other', name='alternativeassettype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_annual_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('last_valuation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternative_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alternative_assets_user_id'), ['user_id'], unique=False)

    op.create_table('asset_valuations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('real_estate', 'vehicle', 'collectible', 'precious_metal', 'alternative', name='assettype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_valuations_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_valuations_user_id'), ['user_id'], unique=False)

    op.create_table('card_benefits',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valuation_method', sa.String(length=50), nullable=True),
    sa.Column('default_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_benefits_card_id'), ['card_id'], unique=False)

    op.create_table('card_credits',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_credits_card_id'), ['card_id'], unique=False)

    op.create_table('collectible_assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.Enum('art', 'watch', 'handbag', 'jewelry', 'wine', 'card', 'other', name='collectibletype'), nullable=False),
    sa.Column('valuation_type', sa.Enum('manual', 'auto', name='valuationtype'), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_annual_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('last_valuation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collectible_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collectible_assets_user_id'), ['user_id'], unique=False)

    op.create_table('connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('credentials', app.db.types.EncryptedJSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', 'pending', name='connectionstatus'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('continuity_status', sa.String(length=50), server_default='healthy', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_user_id'), ['user_id'], unique=False)

    op.create_table('consent_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='consentstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_grants_user_id'), ['user_id'], unique=False)

    op.create_table('crypto_wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('ethereum', 'solana', 'polygon', 'arbitrum', 'base', 'optimism', 'bitcoin', name='cryptochain'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('last_balance_usd', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address', 'chain', name='uq_crypto_wallet_user_address_chain')
    )
    with op.batch_alter_table('crypto_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_wallets_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_crypto_wallets_user_id'), ['user_id'], unique=False)

    op.create_table('entities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('personal', 'c_corp', 's_corp', 'llc', 'spv', 'trust', name='entitytype'), server_default='personal', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_user_id'), ['user_id'], unique=False)

    op.create_table('equity_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('grant_name', sa.String(length=255), nullable=False),
    sa.Column('grant_type', sa.Enum('rsu', 'iso', 'nso', 'restricted_stock', 'phantom_stock', 'safe', 'convertible_note', 'founder_stock', name='equitygranttype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('valuation_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('amount_invested', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_83b_elected', sa.Boolean(), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=True),
    sa.Column('is_qsbs_eligible', sa.Boolean(), nullable=False),
    sa.Column('qsbs_holding_start', sa.Date(), nullable=True),
    sa.Column('vesting_schedule', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_grants_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_grants_user_id'), ['user_id'], unique=False)

    op.create_table('financial_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', name='filingstatus'), nullable=True),
    sa.Column('num_dependents', sa.Integer(), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('federal_tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('state_tax_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('capital_gains_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('retirement_age', sa.Integer(), nullable=True),
    sa.Column('current_retirement_savings', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_retirement_contribution', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employer_match_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_social_security', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('desired_retirement_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('home_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mortgage_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mortgage_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risktolerance'), nullable=True),
    sa.Column('investment_horizon_years', sa.Integer(), nullable=True),
    sa.Column('monthly_savings_target', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('average_monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('emergency_fund_target_months', sa.Integer(), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('employer_industry', sa.String(length=255), nullable=True),
    sa.Column('life_insurance_benefit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('disability_insurance_benefit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('umbrella_policy_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('has_will', sa.Boolean(), nullable=True),
    sa.Column('has_trust', sa.Boolean(), nullable=True),
    sa.Column('has_poa', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('spending_categories_monthly', sa.JSON(), nullable=True),
    sa.Column('debt_profile', sa.JSON(), nullable=True),
    sa.Column('portfolio_summary', sa.JSON(), nullable=True),
    sa.Column('equity_compensation', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_memories_user_id'), ['user_id'], unique=True)

    op.create_table('income_sources',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('salary', 'hourly', 'freelance', 'investment', 'rental', 'other', name='incomesourcetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'semimonthly', 'monthly', 'quarterly', 'annually', name='incomefrequency'), nullable=False),
    sa.Column('is_variable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_sources_user_id'), ['user_id'], unique=False)

    op.create_table('memory_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('user_input', 'calculator', 'account_sync', 'agent', name='memoryeventsource'), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_events_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('low_emergency_fund', 'tax_loss_harvesting', 'data_stale', 'sync_failure', 'policy_breach', 'general', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_investment_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cash_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_debt_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_portfolio_snapshot_user_date')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('precious_metal_assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metal_type', sa.Enum('gold', 'silver', 'platinum', 'palladium', name='metaltype'), nullable=False),
    sa.Column('weight_oz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valuation_type', sa.Enum('manual', 'auto', name='valuationtype'), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_valuation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precious_metal_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precious_metal_assets_user_id'), ['user_id'], unique=False)

    op.create_table('real_estate_assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('property_type', sa.Enum('primary_residence', 'investment_property', 'vacation_home', 'commercial', 'land', name='realestatetype'), nullable=False),
    sa.Column('valuation_type', sa.Enum('manual', 'auto', name='valuationtype'), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_annual_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('zillow_zpid', sa.String(length=100), nullable=True),
    sa.Column('last_valuation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('real_estate_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_real_estate_assets_user_id'), ['user_id'], unique=False)

    op.create_table('share_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_reports_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_reports_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_reports_user_id'), ['user_id'], unique=False)

    op.create_table('tax_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_used', sa.String(length=64), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_documents_user_id'), ['user_id'], unique=False)

    op.create_table('tax_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('household_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_version_id'], ['tax_plan_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_plans_user_id'), ['user_id'], unique=False)

    op.create_table('vehicle_assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('car', 'motorcycle', 'boat', 'aircraft', 'other', name='vehicletype'), nullable=False),
    sa.Column('valuation_type', sa.Enum('manual', 'auto', name='valuationtype'), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_annual_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('last_valuation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_assets_user_id'), ['user_id'], unique=False)

    op.create_table('cash_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'money_market', 'cd', 'other', name='cashaccounttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('apy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('is_manual', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_accounts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('debt_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('debt_type', sa.Enum('credit_card', 'student_loan', 'mortgage', 'auto_loan', 'personal_loan', 'medical', 'other', name='debttype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debt_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('investment_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('brokerage', 'ira', 'roth_ira', '401k', '403b', 'hsa', 'sep_ira', 'simple_ira', 'pension', 'trust', 'other', name='investmentaccounttype'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_tax_advantaged', sa.Boolean(), nullable=False),
    sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_accounts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_accounts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_accounts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', 'needs_review', 'cautious', 'blocked', 'superseded', 'resolved', name='recommendationstatus'), nullable=False),
    sa.Column('superseded_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_by_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('tax_plan_collaborators',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['tax_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_plan_collaborators', schema=None) as batch_op:
        batch_op.create_index('ix_active_collaborator_plan_email', ['plan_id', 'email'], unique=True, postgresql_where='revoked_at IS NULL')
        batch_op.create_index(batch_op.f('ix_tax_plan_collaborators_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_collaborators_invited_by_user_id'), ['invited_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_collaborators_plan_id'), ['plan_id'], unique=False)

    op.create_table('tax_plan_versions',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['tax_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_plan_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_plan_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_versions_plan_id'), ['plan_id'], unique=False)

    op.create_table('bank_transactions',
    sa.Column('cash_account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('detailed_category', sa.String(length=100), nullable=True),
    sa.Column('plaid_category', sa.JSON(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('iso_currency_code', sa.String(length=3), nullable=False),
    sa.Column('reimbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reimbursement_memo', sa.String(length=500), nullable=True),
    sa.Column('is_commingled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_account_id', 'provider_transaction_id', name='uq_bank_tx_account_provider')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transactions_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_primary_category'), ['primary_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('decision_traces',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('trace_type', sa.Enum('recommendation', 'analysis', 'action', name='decisiontracetype'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('reasoning_steps', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('data_freshness', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_traces_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_traces_user_id'), ['user_id'], unique=False)

    op.create_table('holdings',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_security_id'), ['security_id'], unique=False)

    op.create_table('tax_plan_comments',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('author_role', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['tax_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['tax_plan_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_plan_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_plan_comments_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_comments_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_comments_version_id'), ['version_id'], unique=False)

    op.create_table('tax_plan_events',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['tax_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['tax_plan_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_plan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_plan_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_events_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_plan_events_version_id'), ['version_id'], unique=False)

    op.create_table('transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('buy', 'sell', 'dividend', 'interest', 'fee', 'transfer', 'other', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_transaction_id', name='uq_transaction_account_provider_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trade_date'), ['trade_date'], unique=False)

    op.create_table('action_intents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decision_trace_id', sa.Uuid(), nullable=True),
    sa.Column('intent_type', sa.Enum('ach_transfer', 'acats_transfer', 'rebalance', 'tax_loss_harvest', 'open_account', 'custom', name='actionintenttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'processing', 'executed', 'failed', 'cancelled', name='actionintentstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('impact_summary', sa.JSON(), nullable=False),
    sa.Column('execution_manifest', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_trace_id'], ['decision_traces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_intents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_intents_user_id'), ['user_id'], unique=False)

    op.create_table('financial_corrections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=True),
    sa.Column('metric_id', sa.String(length=100), nullable=True),
    sa.Column('correction_type', sa.Enum('wrong_fact', 'stale_fact', 'wrong_categorization', 'wrong_assumption', 'wrong_recommendation', 'intentional_exception', 'source_mistrust', 'execution_mismatch', name='financialcorrectiontype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'applied', 'dismissed', name='financialcorrectionstatus'), nullable=False),
    sa.Column('target_field', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=False),
    sa.Column('proposed_value', sa.JSON(), nullable=False),
    sa.Column('resolved_value', sa.JSON(), nullable=True),
    sa.Column('impact_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_corrections_correction_type'), ['correction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_corrections_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_corrections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_corrections_target_field'), ['target_field'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_corrections_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_corrections_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_reviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decision_trace_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('review_type', sa.Enum('user_dispute', 'outdated', 'human_review', 'context_block', 'factual_followup', name='recommendationreviewtype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', 'converted_to_correction', 'superseded', 'blocked', name='recommendationreviewstatus'), nullable=False),
    sa.Column('opened_reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('applied_changes', sa.JSON(), nullable=False),
    sa.Column('reviewer_label', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_trace_id'], ['decision_traces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_reviews_decision_trace_id'), ['decision_trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_reviews_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_recommendation_reviews_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_reviews_decision_trace_id'))

    op.drop_table('recommendation_reviews')
    with op.batch_alter_table('financial_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_corrections_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_corrections_trace_id'))
        batch_op.drop_index(batch_op.f('ix_financial_corrections_target_field'))
        batch_op.drop_index(batch_op.f('ix_financial_corrections_status'))
        batch_op.drop_index(batch_op.f('ix_financial_corrections_metric_id'))
        batch_op.drop_index(batch_op.f('ix_financial_corrections_correction_type'))

    op.drop_table('financial_corrections')
    with op.batch_alter_table('action_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_intents_status'))

    op.drop_table('action_intents')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_security_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('tax_plan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_plan_events_version_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_events_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_events_event_type'))

    op.drop_table('tax_plan_events')
    with op.batch_alter_table('tax_plan_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_plan_comments_version_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_comments_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_comments_author_user_id'))

    op.drop_table('tax_plan_comments')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_security_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_account_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('decision_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_traces_user_id'))
        batch_op.drop_index(batch_op.f('ix_decision_traces_session_id'))

    op.drop_table('decision_traces')
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_primary_category'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_cash_account_id'))

    op.drop_table('bank_transactions')
    with op.batch_alter_table('tax_plan_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_plan_versions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_versions_created_by_user_id'))

    op.drop_table('tax_plan_versions')
    with op.batch_alter_table('tax_plan_collaborators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_plan_collaborators_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_collaborators_invited_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_tax_plan_collaborators_email'))
        batch_op.drop_index('ix_active_collaborator_plan_email', postgresql_where='revoked_at IS NULL')

    op.drop_table('tax_plan_collaborators')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('investment_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_investment_accounts_institution_id'))
        batch_op.drop_index(batch_op.f('ix_investment_accounts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_investment_accounts_connection_id'))

    op.drop_table('investment_accounts')
    with op.batch_alter_table('debt_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_debt_accounts_entity_id'))

    op.drop_table('debt_accounts')
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_cash_accounts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_cash_accounts_connection_id'))

    op.drop_table('cash_accounts')
    with op.batch_alter_table('vehicle_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_assets_user_id'))

    op.drop_table('vehicle_assets')
    with op.batch_alter_table('tax_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_plans_user_id'))

    op.drop_table('tax_plans')
    with op.batch_alter_table('tax_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_documents_user_id'))

    op.drop_table('tax_documents')
    with op.batch_alter_table('share_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_reports_tool_id'))
        batch_op.drop_index(batch_op.f('ix_share_reports_token_hash'))

    op.drop_table('share_reports')
    with op.batch_alter_table('real_estate_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_real_estate_assets_user_id'))

    op.drop_table('real_estate_assets')
    with op.batch_alter_table('precious_metal_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precious_metal_assets_user_id'))

    op.drop_table('precious_metal_assets')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_snapshot_date'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_events_user_id'))

    op.drop_table('memory_events')
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_sources_user_id'))

    op.drop_table('income_sources')
    with op.batch_alter_table('financial_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_memories_user_id'))

    op.drop_table('financial_memories')
    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_equity_grants_symbol'))

    op.drop_table('equity_grants')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_user_id'))

    op.drop_table('entities')
    with op.batch_alter_table('crypto_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_crypto_wallets_address'))

    op.drop_table('crypto_wallets')
    with op.batch_alter_table('consent_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_grants_user_id'))

    op.drop_table('consent_grants')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_connections_institution_id'))

    op.drop_table('connections')
    with op.batch_alter_table('collectible_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collectible_assets_user_id'))

    op.drop_table('collectible_assets')
    with op.batch_alter_table('card_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_credits_card_id'))

    op.drop_table('card_credits')
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_benefits_card_id'))

    op.drop_table('card_benefits')
    with op.batch_alter_table('asset_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_valuations_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_valuations_asset_id'))

    op.drop_table('asset_valuations')
    with op.batch_alter_table('alternative_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alternative_assets_user_id'))

    op.drop_table('alternative_assets')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_user_id'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('agent_action_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_action_policies_user_id'))

    op.drop_table('agent_action_policies')
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_approvals_user_id'))

    op.drop_table('action_approvals')
    with op.batch_alter_table('waitlist_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_waitlist_users_email'))

    op.drop_table('waitlist_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_clerk_id'))

    op.drop_table('users')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_ticker'))

    op.drop_table('securities')
    op.drop_table('institutions')
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cards_issuer'))

    op.drop_table('credit_cards')
    # ### end Alembic commands ###
