"""add_profile_fields_to_financial_memory

Revision ID: bc7ee1367c64
Revises: ed6b3a5c3da5
Create Date: 2026-03-25 13:11:33.251650

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc7ee1367c64'
down_revision: Union[str, Sequence[str], None] = 'ed6b3a5c3da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_83b_elected', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('election_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_qsbs_eligible', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('qsbs_holding_start', sa.Date(), nullable=True))

    with op.batch_alter_table('financial_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employer_industry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('life_insurance_benefit', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('disability_insurance_benefit', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('umbrella_policy_limit', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('has_will', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_trust', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_poa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)

    with op.batch_alter_table('waitlist_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False,
               existing_server_default=sa.text('(uuid_generate_v4())'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(uuid_generate_v4())'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('financial_memories', schema=None) as batch_op:
        batch_op.drop_column('entity_type')
        batch_op.drop_column('has_poa')
        batch_op.drop_column('has_trust')
        batch_op.drop_column('has_will')
        batch_op.drop_column('umbrella_policy_limit')
        batch_op.drop_column('disability_insurance_benefit')
        batch_op.drop_column('life_insurance_benefit')
        batch_op.drop_column('employer_industry')
        batch_op.drop_column('employer_name')

    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.drop_column('qsbs_holding_start')
        batch_op.drop_column('is_qsbs_eligible')
        batch_op.drop_column('election_date')
        batch_op.drop_column('is_83b_elected')

    # ### end Alembic commands ###
