"""Add cap table fields to equity grant

Revision ID: cc448bef9bfd
Revises: 0106a4809fa7
Create Date: 2026-03-05 11:21:24.418181

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc448bef9bfd'
down_revision: Union[str, Sequence[str], None] = '0106a4809fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('grant_name', sa.String(length=255), nullable=False),
    sa.Column('grant_type', sa.Enum('rsu', 'iso', 'nso', 'restricted_stock', 'phantom_stock', 'safe', 'convertible_note', 'founder_stock', name='equitygranttype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('valuation_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('amount_invested', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vesting_schedule', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_grants_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_grants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equity_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_equity_grants_symbol'))

    op.drop_table('equity_grants')
    # ### end Alembic commands ###
