"""add_decision_traces

Revision ID: e7a1b2c3d4e5
Revises: d2c3d4e5f6a7
Create Date: 2026-02-01 12:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7a1b2c3d4e5'
down_revision: Union[str, Sequence[str], None] = 'd2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'decision_traces',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('session_id', sa.Uuid(), nullable=False),
        sa.Column('recommendation_id', sa.Uuid(), nullable=True),
        sa.Column(
            'trace_type',
            sa.Enum('recommendation', 'analysis', 'action', name='decisiontracetype'),
            nullable=False,
        ),
        sa.Column('input_data', sa.JSON(), nullable=False),
        sa.Column('reasoning_steps', sa.JSON(), nullable=False),
        sa.Column('outputs', sa.JSON(), nullable=False),
        sa.Column('data_freshness', sa.JSON(), nullable=False),
        sa.Column('warnings', sa.JSON(), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_decision_traces_session_id'), 'decision_traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_decision_traces_user_id'), 'decision_traces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_traces_user_id'), table_name='decision_traces')
    op.drop_index(op.f('ix_decision_traces_session_id'), table_name='decision_traces')
    op.drop_table('decision_traces')
    # ### end Alembic commands ###
