"""add plan to user

Revision ID: ed6b3a5c3da5
Revises: a582acc13bf7
Create Date: 2026-03-23 15:15:22.016774

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed6b3a5c3da5'
down_revision: Union[str, Sequence[str], None] = 'a582acc13bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
