"""add_consent_grants

Revision ID: f2b3c4d5e6f7
Revises: e7a1b2c3d4e5
Create Date: 2026-02-01 12:30:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2b3c4d5e6f7'
down_revision: Union[str, Sequence[str], None] = 'e7a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'consent_grants',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('scopes', sa.JSON(), nullable=False),
        sa.Column('purpose', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('active', 'revoked', 'expired', name='consentstatus'),
            nullable=False,
        ),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_consent_grants_user_id'), 'consent_grants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_grants_user_id'), table_name='consent_grants')
    op.drop_table('consent_grants')
    # ### end Alembic commands ###
