import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using ClearMoney.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#fafafa] dark:bg-slate-950 transition-colors">
      <main className="max-w-3xl mx-auto px-6 lg:px-8 py-20">
        <p className="text-sm font-bold uppercase tracking-widest text-emerald-600 dark:text-emerald-400 mb-4">
          Legal
        </p>
        <h1 className="font-display text-4xl text-slate-900 dark:text-white mb-4">
          Terms of Service
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mb-12">
          Last updated: February 2026
        </p>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8 text-slate-700 dark:text-slate-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">1. Service Description</h2>
            <p>
              ClearMoney is a financial operating system that aggregates your financial data,
              provides personalized analysis, and generates actionable recommendations. ClearMoney
              is not a registered investment advisor, broker-dealer, or financial planner. The
              information provided is for educational and informational purposes only and should
              not be construed as personalized financial advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">2. Beta Program</h2>
            <p>
              ClearMoney is currently in private beta. The service is provided &quot;as is&quot;
              during this period. Features may change, and we may experience downtime or data
              inconsistencies as we iterate. By participating in the beta, you acknowledge these
              limitations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">3. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You
              agree to provide accurate information and to keep your connected financial accounts
              up to date. You must be at least 18 years old to use ClearMoney.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">4. Data Accuracy</h2>
            <p>
              While we strive for accuracy, ClearMoney relies on data from third-party providers
              (Plaid, SnapTrade) and user input. We cannot guarantee that all financial data is
              complete, current, or error-free. Always verify important financial decisions with
              your own records and qualified professionals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">5. Not Financial Advice</h2>
            <p>
              ClearMoney&apos;s recommendations, decision traces, and analysis are generated by
              algorithms and AI models. They are not a substitute for professional financial,
              tax, or legal advice. You are solely responsible for any financial decisions you
              make based on information from ClearMoney.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">6. Our Transparency Pledge</h2>
            <p>
              Every recommendation on ClearMoney includes a decision trace showing the inputs,
              logic, and confidence score. If we earn affiliate revenue from a recommendation, we
              disclose it. We will never rank a product higher because of its payout.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">7. Termination</h2>
            <p>
              You may delete your account at any time. We reserve the right to suspend or
              terminate accounts that violate these terms or abuse the service. Upon termination,
              your data will be permanently deleted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">8. Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href="mailto:legal@clearmoney.com" className="text-emerald-600 dark:text-emerald-400 hover:underline">
                legal@clearmoney.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-slate-200 dark:border-slate-800">
          <Link
            href="/"
            className="text-sm font-bold text-emerald-600 dark:text-emerald-400 hover:text-emerald-500 transition-colors"
          >
            &larr; Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
